import { Article } from './types';

export const allArticles: Article[] = [
  // RBI Policy - 10 Articles
  {
    id: 'rbi-1',
    title: 'RBI Monetary Policy: Key Highlights for Banking Exams',
    category: 'Banking',
    importance: 'high',
    excerpt: 'Reserve Bank of India announces new policy rates. Key points every banking aspirant must know for IBPS, SBI exams.',
    content: `The Reserve Bank of India (RBI) in its latest Monetary Policy Committee (MPC) meeting has announced several key decisions...`,
    readTime: '5 min',
    date: 'January 20, 2025',
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&h=250&fit=crop',
    tags: ['#RBI', '#Banking', '#MonetaryPolicy'],
    topic: 'RBI Policy',
    relatedIds: ['rbi-2', 'rbi-3'],
    hasQuiz: true,
    quizQuestions: 10,
  },
  {
    id: 'rbi-2',
    title: 'RBI Introduces New Digital Lending Guidelines 2025',
    category: 'Banking',
    importance: 'high',
    excerpt: 'Comprehensive framework for digital lending apps and NBFCs. Important for RBI Grade B and NABARD exams.',
    content: `The Reserve Bank of India has released updated digital lending guidelines to protect borrowers...`,
    readTime: '6 min',
    date: 'January 19, 2025',
    image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=400&h=250&fit=crop',
    tags: ['#RBI', '#DigitalLending', '#FinTech'],
    topic: 'RBI Policy',
    relatedIds: ['rbi-1', 'rbi-4'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'rbi-3',
    title: 'SEBI Introduces New Regulations for Market Intermediaries',
    category: 'Banking',
    importance: 'high',
    excerpt: 'Must-know for RBI Grade B and SEBI Grade A exam aspirants. Complete analysis of new market regulations.',
    content: `Securities and Exchange Board of India (SEBI) has introduced comprehensive new regulations...`,
    readTime: '7 min',
    date: 'January 18, 2025',
    image: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=400&h=250&fit=crop',
    tags: ['#SEBI', '#Banking', '#Markets'],
    topic: 'RBI Policy',
    relatedIds: ['rbi-1', 'rbi-5'],
    hasQuiz: true,
    quizQuestions: 12,
  },
  {
    id: 'rbi-4',
    title: 'RBI Revises Priority Sector Lending Norms',
    category: 'Banking',
    importance: 'medium',
    excerpt: 'Updated PSL targets for banks and small finance banks. Essential for IBPS PO and SBI PO preparations.',
    content: `The Reserve Bank has revised priority sector lending targets with focus on agriculture and MSME...`,
    readTime: '5 min',
    date: 'January 17, 2025',
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400&h=250&fit=crop',
    tags: ['#RBI', '#PSL', '#Banking'],
    topic: 'RBI Policy',
    relatedIds: ['rbi-2', 'rbi-6'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'rbi-5',
    title: 'UPI Transaction Limits Increased by RBI',
    category: 'Banking',
    importance: 'high',
    excerpt: 'RBI doubles UPI transaction limits for specific categories. Important update for banking exams.',
    content: `In a major boost to digital payments, RBI has increased UPI transaction limits...`,
    readTime: '4 min',
    date: 'January 16, 2025',
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&h=250&fit=crop',
    tags: ['#UPI', '#RBI', '#DigitalPayments'],
    topic: 'RBI Policy',
    relatedIds: ['rbi-3', 'rbi-7'],
    hasQuiz: true,
    quizQuestions: 6,
  },
  {
    id: 'rbi-6',
    title: 'RBI Launches Central Bank Digital Currency Pilot Phase 2',
    category: 'Banking',
    importance: 'high',
    excerpt: 'e-Rupee pilot expanded to more cities and banks. Complete CBDC framework analysis for exams.',
    content: `The Reserve Bank has expanded its CBDC pilot program with new features and more participating banks...`,
    readTime: '8 min',
    date: 'January 15, 2025',
    image: 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=400&h=250&fit=crop',
    tags: ['#CBDC', '#eRupee', '#RBI'],
    topic: 'RBI Policy',
    relatedIds: ['rbi-4', 'rbi-8'],
    hasQuiz: true,
    quizQuestions: 10,
  },
  {
    id: 'rbi-7',
    title: 'Banking Sector NPAs Decline: RBI Financial Stability Report',
    category: 'Banking',
    importance: 'medium',
    excerpt: 'Gross NPAs at decade low. Key statistics from FSR for banking exam preparations.',
    content: `The Financial Stability Report shows continued improvement in asset quality of banks...`,
    readTime: '6 min',
    date: 'January 14, 2025',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=250&fit=crop',
    tags: ['#NPA', '#Banking', '#FSR'],
    topic: 'RBI Policy',
    relatedIds: ['rbi-5', 'rbi-9'],
    hasQuiz: false,
  },
  {
    id: 'rbi-8',
    title: 'RBI Fines Multiple Banks for KYC Violations',
    category: 'Banking',
    importance: 'medium',
    excerpt: 'Regulatory action against banks for compliance failures. Important for understanding RBI supervisory role.',
    content: `RBI has imposed monetary penalties on several banks for non-compliance with KYC norms...`,
    readTime: '4 min',
    date: 'January 13, 2025',
    image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=400&h=250&fit=crop',
    tags: ['#RBI', '#KYC', '#Compliance'],
    topic: 'RBI Policy',
    relatedIds: ['rbi-6', 'rbi-10'],
    hasQuiz: false,
  },
  {
    id: 'rbi-9',
    title: 'Interest Rate Corridor: Understanding LAF Framework',
    category: 'Banking',
    importance: 'medium',
    excerpt: 'Complete guide to Liquidity Adjustment Facility. Essential concept for all banking exams.',
    content: `The LAF corridor mechanism is central to RBI's monetary policy transmission...`,
    readTime: '7 min',
    date: 'January 12, 2025',
    image: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=400&h=250&fit=crop',
    tags: ['#LAF', '#RBI', '#MonetaryPolicy'],
    topic: 'RBI Policy',
    relatedIds: ['rbi-7', 'rbi-1'],
    hasQuiz: true,
    quizQuestions: 10,
  },
  {
    id: 'rbi-10',
    title: 'RBI Annual Report 2024-25: Key Takeaways',
    category: 'Banking',
    importance: 'high',
    excerpt: 'Important statistics and policy insights from RBI Annual Report. Must-read for banking aspirants.',
    content: `The RBI Annual Report provides comprehensive overview of monetary and banking developments...`,
    readTime: '10 min',
    date: 'January 11, 2025',
    image: 'https://images.unsplash.com/photo-1554224154-22dec7ec8818?w=400&h=250&fit=crop',
    tags: ['#RBI', '#AnnualReport', '#Banking'],
    topic: 'RBI Policy',
    relatedIds: ['rbi-8', 'rbi-2'],
    hasQuiz: true,
    quizQuestions: 15,
  },

  // Budget 2025 - 10 Articles
  {
    id: 'budget-1',
    title: 'Union Budget 2025-26: Complete Analysis for Competitive Exams',
    category: 'Economy',
    importance: 'high',
    excerpt: 'Comprehensive breakdown of the budget with focus on questions likely to appear in SSC, UPSC, and banking exams.',
    content: `The Union Budget 2025-26 presented by the Finance Minister introduces several landmark initiatives...`,
    readTime: '12 min',
    date: 'January 22, 2025',
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400&h=250&fit=crop',
    tags: ['#Budget2025', '#Economy', '#UPSC'],
    topic: 'Budget 2025',
    relatedIds: ['budget-2', 'budget-3'],
    hasQuiz: true,
    quizQuestions: 20,
  },
  {
    id: 'budget-2',
    title: 'New Income Tax Slabs: Budget 2025 Tax Reforms',
    category: 'Economy',
    importance: 'high',
    excerpt: 'Revised income tax structure under new regime. Important for all competitive exams.',
    content: `The Budget introduces significant changes to income tax slabs benefiting middle class...`,
    readTime: '6 min',
    date: 'January 22, 2025',
    image: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=400&h=250&fit=crop',
    tags: ['#IncomeTax', '#Budget2025', '#TaxReforms'],
    topic: 'Budget 2025',
    relatedIds: ['budget-1', 'budget-4'],
    hasQuiz: true,
    quizQuestions: 10,
  },
  {
    id: 'budget-3',
    title: 'Infrastructure Push: ₹11 Lakh Crore Capex Allocation',
    category: 'Economy',
    importance: 'high',
    excerpt: 'Record capital expenditure for infrastructure development. Key projects and allocations.',
    content: `The government has allocated unprecedented funds for infrastructure with focus on railways, roads...`,
    readTime: '8 min',
    date: 'January 21, 2025',
    image: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=400&h=250&fit=crop',
    tags: ['#Infrastructure', '#Budget2025', '#Capex'],
    topic: 'Budget 2025',
    relatedIds: ['budget-1', 'budget-5'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'budget-4',
    title: 'Agriculture Sector: Budget 2025 Highlights',
    category: 'Economy',
    importance: 'medium',
    excerpt: 'PM-KISAN enhancement and agricultural reforms. Essential for UPSC and state PSC exams.',
    content: `The Budget focuses on farmer welfare with increased MSP support and irrigation projects...`,
    readTime: '7 min',
    date: 'January 21, 2025',
    image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=400&h=250&fit=crop',
    tags: ['#Agriculture', '#Budget2025', '#PMKISAN'],
    topic: 'Budget 2025',
    relatedIds: ['budget-2', 'budget-6'],
    hasQuiz: true,
    quizQuestions: 10,
  },
  {
    id: 'budget-5',
    title: 'Defence Budget 2025: Modernization Plans',
    category: 'Economy',
    importance: 'medium',
    excerpt: 'Record defence allocation with focus on indigenous manufacturing. Important for NDA/CDS exams.',
    content: `Defence budget sees significant increase with emphasis on Atmanirbhar Bharat in defence...`,
    readTime: '6 min',
    date: 'January 20, 2025',
    image: 'https://images.unsplash.com/photo-1569974507005-6dc61f97fb5c?w=400&h=250&fit=crop',
    tags: ['#Defence', '#Budget2025', '#Military'],
    topic: 'Budget 2025',
    relatedIds: ['budget-3', 'budget-7'],
    hasQuiz: false,
  },
  {
    id: 'budget-6',
    title: 'Education and Skill Development Allocations',
    category: 'Economy',
    importance: 'medium',
    excerpt: 'Increased funding for education sector and skill development programs under Budget 2025.',
    content: `The Budget prioritizes education with new schemes for digital learning and skill enhancement...`,
    readTime: '5 min',
    date: 'January 20, 2025',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=400&h=250&fit=crop',
    tags: ['#Education', '#Budget2025', '#SkillDevelopment'],
    topic: 'Budget 2025',
    relatedIds: ['budget-4', 'budget-8'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'budget-7',
    title: 'Green Energy Transition Fund: Budget 2025',
    category: 'Economy',
    importance: 'high',
    excerpt: 'Major push for renewable energy and sustainability. Climate action funding details.',
    content: `Budget allocates significant funds for green hydrogen, solar manufacturing and EV infrastructure...`,
    readTime: '7 min',
    date: 'January 19, 2025',
    image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400&h=250&fit=crop',
    tags: ['#GreenEnergy', '#Budget2025', '#Climate'],
    topic: 'Budget 2025',
    relatedIds: ['budget-5', 'budget-9'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'budget-8',
    title: 'Fiscal Deficit Target and Borrowing Program',
    category: 'Economy',
    importance: 'high',
    excerpt: 'Government aims for fiscal consolidation. Understanding deficit financing for exams.',
    content: `The Budget targets fiscal deficit at 4.9% of GDP, continuing path of fiscal consolidation...`,
    readTime: '6 min',
    date: 'January 19, 2025',
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&h=250&fit=crop',
    tags: ['#FiscalDeficit', '#Budget2025', '#Economy'],
    topic: 'Budget 2025',
    relatedIds: ['budget-6', 'budget-10'],
    hasQuiz: true,
    quizQuestions: 10,
  },
  {
    id: 'budget-9',
    title: 'Healthcare Budget: Ayushman Bharat Expansion',
    category: 'Economy',
    importance: 'medium',
    excerpt: 'Health sector allocations and new medical infrastructure projects announced.',
    content: `The Budget expands Ayushman Bharat coverage and announces new AIIMS and medical colleges...`,
    readTime: '5 min',
    date: 'January 18, 2025',
    image: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=400&h=250&fit=crop',
    tags: ['#Healthcare', '#Budget2025', '#AyushmanBharat'],
    topic: 'Budget 2025',
    relatedIds: ['budget-7', 'budget-1'],
    hasQuiz: false,
  },
  {
    id: 'budget-10',
    title: 'GST Revenue and Indirect Tax Reforms',
    category: 'Economy',
    importance: 'medium',
    excerpt: 'GST collection trends and proposed indirect tax changes. Important for commerce exams.',
    content: `Record GST collections signal economic recovery. Budget proposes GST rate rationalization...`,
    readTime: '6 min',
    date: 'January 18, 2025',
    image: 'https://images.unsplash.com/photo-1554224154-22dec7ec8818?w=400&h=250&fit=crop',
    tags: ['#GST', '#Budget2025', '#IndirectTax'],
    topic: 'Budget 2025',
    relatedIds: ['budget-8', 'budget-2'],
    hasQuiz: true,
    quizQuestions: 10,
  },

  // Defence - 10 Articles
  {
    id: 'defence-1',
    title: 'Defence Acquisition Council Approves New Projects',
    category: 'National',
    importance: 'high',
    excerpt: 'Important for NDA, CDS, and UPSC aspirants. New defence projects worth ₹15,000 crores approved.',
    content: `The Defence Acquisition Council (DAC) has approved several significant projects...`,
    readTime: '5 min',
    date: 'January 20, 2025',
    image: 'https://images.unsplash.com/photo-1580752300992-559f8e898998?w=400&h=250&fit=crop',
    tags: ['#Defence', '#DAC', '#Military'],
    topic: 'Defence',
    relatedIds: ['defence-2', 'defence-3'],
    hasQuiz: true,
    quizQuestions: 10,
  },
  {
    id: 'defence-2',
    title: 'Tejas Mark 2 Development: Major Milestone Achieved',
    category: 'National',
    importance: 'high',
    excerpt: 'Indigenous fighter jet program reaches critical design review. Important for defence exams.',
    content: `HAL and DRDO announce major progress in Tejas Mark 2 advanced light combat aircraft...`,
    readTime: '6 min',
    date: 'January 19, 2025',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=250&fit=crop',
    tags: ['#Tejas', '#HAL', '#IndigenousDefence'],
    topic: 'Defence',
    relatedIds: ['defence-1', 'defence-4'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'defence-3',
    title: 'India-France Defence Partnership: Rafale Marine Deal',
    category: 'National',
    importance: 'high',
    excerpt: 'Strategic partnership strengthened with new naval fighter acquisition for INS Vikrant.',
    content: `India and France sign major defence deal for Rafale Marine aircraft for aircraft carrier...`,
    readTime: '7 min',
    date: 'January 18, 2025',
    image: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=400&h=250&fit=crop',
    tags: ['#Rafale', '#IndiaFrance', '#NavalAviation'],
    topic: 'Defence',
    relatedIds: ['defence-2', 'defence-5'],
    hasQuiz: false,
  },
  {
    id: 'defence-4',
    title: 'BrahMos Supersonic Cruise Missile: Extended Range Version',
    category: 'National',
    importance: 'medium',
    excerpt: 'Successful test of extended range BrahMos missile. Key facts for defence exams.',
    content: `India successfully tests extended range version of BrahMos cruise missile...`,
    readTime: '4 min',
    date: 'January 17, 2025',
    image: 'https://images.unsplash.com/photo-1517976487492-5750f3195933?w=400&h=250&fit=crop',
    tags: ['#BrahMos', '#Missiles', '#DRDO'],
    topic: 'Defence',
    relatedIds: ['defence-3', 'defence-6'],
    hasQuiz: true,
    quizQuestions: 6,
  },
  {
    id: 'defence-5',
    title: 'Indian Navy Commissions New Destroyer INS Visakhapatnam Class',
    category: 'National',
    importance: 'medium',
    excerpt: 'Project 15B destroyer commissioned. Naval modernization update for aspirants.',
    content: `The Indian Navy adds new stealth destroyer to its fleet under Project 15B...`,
    readTime: '5 min',
    date: 'January 16, 2025',
    image: 'https://images.unsplash.com/photo-1569974507005-6dc61f97fb5c?w=400&h=250&fit=crop',
    tags: ['#IndianNavy', '#INSVisakhapatnam', '#NavalPower'],
    topic: 'Defence',
    relatedIds: ['defence-4', 'defence-7'],
    hasQuiz: false,
  },
  {
    id: 'defence-6',
    title: 'Agnipath Scheme: Two Years of Implementation Review',
    category: 'National',
    importance: 'medium',
    excerpt: 'Analysis of Agnipath military recruitment scheme. Important for defence and UPSC exams.',
    content: `Comprehensive review of Agnipath scheme after two years of implementation...`,
    readTime: '8 min',
    date: 'January 15, 2025',
    image: 'https://images.unsplash.com/photo-1534030347209-467a5b0ad3e6?w=400&h=250&fit=crop',
    tags: ['#Agnipath', '#Agniveer', '#MilitaryRecruitment'],
    topic: 'Defence',
    relatedIds: ['defence-5', 'defence-8'],
    hasQuiz: true,
    quizQuestions: 10,
  },
  {
    id: 'defence-7',
    title: 'India Develops Indigenous Aircraft Carrier Design',
    category: 'National',
    importance: 'high',
    excerpt: 'IAC-2 design finalized with indigenous CATOBAR system. Major naval development.',
    content: `India moves forward with second indigenous aircraft carrier with advanced launch systems...`,
    readTime: '6 min',
    date: 'January 14, 2025',
    image: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=400&h=250&fit=crop',
    tags: ['#IAC2', '#AircraftCarrier', '#IndianNavy'],
    topic: 'Defence',
    relatedIds: ['defence-6', 'defence-9'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'defence-8',
    title: 'Cyber Command: India Establishes Tri-Service Cyber Agency',
    category: 'National',
    importance: 'high',
    excerpt: 'New unified cyber command for armed forces. Important for understanding modern warfare.',
    content: `India establishes Defence Cyber Agency to handle cyber warfare capabilities...`,
    readTime: '5 min',
    date: 'January 13, 2025',
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop',
    tags: ['#CyberSecurity', '#DefenceCyber', '#ModernWarfare'],
    topic: 'Defence',
    relatedIds: ['defence-7', 'defence-10'],
    hasQuiz: false,
  },
  {
    id: 'defence-9',
    title: 'India-US Defence Trade: New Agreements Signed',
    category: 'National',
    importance: 'medium',
    excerpt: 'Strategic defence partnership with USA strengthened. Important for international relations.',
    content: `India and US sign new defence agreements including jet engine co-production...`,
    readTime: '6 min',
    date: 'January 12, 2025',
    image: 'https://images.unsplash.com/photo-1532375810709-75b1da00537c?w=400&h=250&fit=crop',
    tags: ['#IndiaUS', '#DefenceTrade', '#StrategicPartnership'],
    topic: 'Defence',
    relatedIds: ['defence-8', 'defence-1'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'defence-10',
    title: 'DRDO Successfully Tests Anti-Satellite Weapon',
    category: 'National',
    importance: 'high',
    excerpt: 'India demonstrates ASAT capability. Space warfare and defence technology update.',
    content: `DRDO successfully demonstrates advanced anti-satellite weapon system capability...`,
    readTime: '5 min',
    date: 'January 11, 2025',
    image: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=400&h=250&fit=crop',
    tags: ['#DRDO', '#ASAT', '#SpaceDefence'],
    topic: 'Defence',
    relatedIds: ['defence-9', 'defence-2'],
    hasQuiz: true,
    quizQuestions: 8,
  },

  // Space & ISRO - 10 Articles
  {
    id: 'isro-1',
    title: 'Chandrayaan-4: Moon Sample Return Mission Announced',
    category: 'Science',
    importance: 'high',
    excerpt: 'ISRO announces ambitious lunar sample return mission. Major milestone for space program.',
    content: `ISRO unveils plans for Chandrayaan-4 mission to bring back lunar samples...`,
    readTime: '8 min',
    date: 'January 21, 2025',
    image: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=400&h=250&fit=crop',
    tags: ['#Chandrayaan4', '#ISRO', '#MoonMission'],
    topic: 'Space & ISRO',
    relatedIds: ['isro-2', 'isro-3'],
    hasQuiz: true,
    quizQuestions: 12,
  },
  {
    id: 'isro-2',
    title: 'Gaganyaan: Uncrewed Test Flight Successful',
    category: 'Science',
    importance: 'high',
    excerpt: 'India moves closer to human spaceflight with successful uncrewed mission test.',
    content: `ISRO successfully completes crucial uncrewed test flight of Gaganyaan spacecraft...`,
    readTime: '7 min',
    date: 'January 20, 2025',
    image: 'https://images.unsplash.com/photo-1457364559154-aa2644600ebb?w=400&h=250&fit=crop',
    tags: ['#Gaganyaan', '#ISRO', '#HumanSpaceflight'],
    topic: 'Space & ISRO',
    relatedIds: ['isro-1', 'isro-4'],
    hasQuiz: true,
    quizQuestions: 10,
  },
  {
    id: 'isro-3',
    title: 'GSAT-24 Communication Satellite Successfully Launched',
    category: 'Science',
    importance: 'medium',
    excerpt: 'ISRO strengthens communication infrastructure with new satellite launch.',
    content: `GSAT-24 launched successfully using GSLV Mk III to boost pan-India connectivity...`,
    readTime: '5 min',
    date: 'January 19, 2025',
    image: 'https://images.unsplash.com/photo-1516849841032-87cbac4d88f7?w=400&h=250&fit=crop',
    tags: ['#GSAT24', '#ISRO', '#Communication'],
    topic: 'Space & ISRO',
    relatedIds: ['isro-2', 'isro-5'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'isro-4',
    title: 'SSLV: Small Satellite Launch Vehicle Declared Operational',
    category: 'Science',
    importance: 'medium',
    excerpt: 'ISRO\'s small satellite launcher ready for commercial operations.',
    content: `SSLV successfully completes all development flights, declared operational...`,
    readTime: '4 min',
    date: 'January 18, 2025',
    image: 'https://images.unsplash.com/photo-1517976487492-5750f3195933?w=400&h=250&fit=crop',
    tags: ['#SSLV', '#ISRO', '#SmallSatellites'],
    topic: 'Space & ISRO',
    relatedIds: ['isro-3', 'isro-6'],
    hasQuiz: false,
  },
  {
    id: 'isro-5',
    title: 'India-NASA Joint Earth Observation Mission NISAR',
    category: 'Science',
    importance: 'high',
    excerpt: 'Indo-US satellite for earth observation and climate monitoring launched.',
    content: `NISAR satellite launched for monitoring Earth\'s ecosystems and ice mass changes...`,
    readTime: '6 min',
    date: 'January 17, 2025',
    image: 'https://images.unsplash.com/photo-1614730321146-b6fa6a46bcb4?w=400&h=250&fit=crop',
    tags: ['#NISAR', '#ISRO', '#NASA', '#EarthObservation'],
    topic: 'Space & ISRO',
    relatedIds: ['isro-4', 'isro-7'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'isro-6',
    title: 'Aditya-L1: Solar Observatory Begins Science Operations',
    category: 'Science',
    importance: 'high',
    excerpt: 'India\'s solar mission starts sending crucial data about the Sun.',
    content: `Aditya-L1 reaches final orbit at L1 point and begins scientific observations...`,
    readTime: '7 min',
    date: 'January 16, 2025',
    image: 'https://images.unsplash.com/photo-1532693322450-2cb5c511067d?w=400&h=250&fit=crop',
    tags: ['#AdityaL1', '#ISRO', '#SolarMission'],
    topic: 'Space & ISRO',
    relatedIds: ['isro-5', 'isro-8'],
    hasQuiz: true,
    quizQuestions: 10,
  },
  {
    id: 'isro-7',
    title: 'IN-SPACe Approves Private Sector Space Missions',
    category: 'Science',
    importance: 'medium',
    excerpt: 'Indian space startups get clearance for satellite launches. Space sector reforms.',
    content: `IN-SPACe authorizes multiple private space companies for launch operations...`,
    readTime: '5 min',
    date: 'January 15, 2025',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=250&fit=crop',
    tags: ['#INSPACe', '#SpaceStartups', '#PrivateSpace'],
    topic: 'Space & ISRO',
    relatedIds: ['isro-6', 'isro-9'],
    hasQuiz: false,
  },
  {
    id: 'isro-8',
    title: 'NavIC: Indian Regional Navigation System Expansion',
    category: 'Science',
    importance: 'medium',
    excerpt: 'NavIC coverage expanded with new satellites. Indigenous GPS alternative strengthened.',
    content: `ISRO launches new satellites to enhance NavIC coverage and accuracy...`,
    readTime: '5 min',
    date: 'January 14, 2025',
    image: 'https://images.unsplash.com/photo-1498036882173-b41c28a8ba34?w=400&h=250&fit=crop',
    tags: ['#NavIC', '#ISRO', '#Navigation'],
    topic: 'Space & ISRO',
    relatedIds: ['isro-7', 'isro-10'],
    hasQuiz: true,
    quizQuestions: 6,
  },
  {
    id: 'isro-9',
    title: 'Reusable Launch Vehicle: RLV-TD Flight Test',
    category: 'Science',
    importance: 'high',
    excerpt: 'ISRO advances reusable rocket technology with successful landing test.',
    content: `RLV technology demonstrator completes autonomous landing test successfully...`,
    readTime: '6 min',
    date: 'January 13, 2025',
    image: 'https://images.unsplash.com/photo-1541185933-55f6926b8ced?w=400&h=250&fit=crop',
    tags: ['#RLV', '#ISRO', '#ReusableRocket'],
    topic: 'Space & ISRO',
    relatedIds: ['isro-8', 'isro-1'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'isro-10',
    title: 'Venus Orbiter Mission: Shukrayaan-1 Update',
    category: 'Science',
    importance: 'medium',
    excerpt: 'ISRO prepares for Venus mission. Planetary exploration program expansion.',
    content: `Shukrayaan-1 Venus orbiter mission development progresses with payload finalization...`,
    readTime: '5 min',
    date: 'January 12, 2025',
    image: 'https://images.unsplash.com/photo-1614732414444-096e5f1122d5?w=400&h=250&fit=crop',
    tags: ['#Shukrayaan', '#Venus', '#ISRO'],
    topic: 'Space & ISRO',
    relatedIds: ['isro-9', 'isro-2'],
    hasQuiz: false,
  },

  // International Relations - 10 Articles
  {
    id: 'intl-1',
    title: 'India Signs Historic Trade Agreement with EU Nations',
    category: 'International',
    importance: 'high',
    excerpt: 'Historic trade deal expected to boost exports. Key facts for UPSC and commerce exams.',
    content: `India signs landmark Free Trade Agreement with the European Union...`,
    readTime: '8 min',
    date: 'January 21, 2025',
    image: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=400&h=250&fit=crop',
    tags: ['#IndiaEU', '#FTA', '#Trade'],
    topic: 'International Relations',
    relatedIds: ['intl-2', 'intl-3'],
    hasQuiz: true,
    quizQuestions: 10,
  },
  {
    id: 'intl-2',
    title: 'G20 Summit 2025: Key Outcomes and Agreements',
    category: 'International',
    importance: 'high',
    excerpt: 'Major global summit conclusions and India\'s role. Essential for international affairs.',
    content: `G20 leaders agree on climate finance, digital taxation and global health preparedness...`,
    readTime: '10 min',
    date: 'January 20, 2025',
    image: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=400&h=250&fit=crop',
    tags: ['#G20', '#GlobalDiplomacy', '#India'],
    topic: 'International Relations',
    relatedIds: ['intl-1', 'intl-4'],
    hasQuiz: true,
    quizQuestions: 12,
  },
  {
    id: 'intl-3',
    title: 'QUAD Summit: Indo-Pacific Security Framework',
    category: 'International',
    importance: 'high',
    excerpt: 'Quad nations strengthen security cooperation. Important for defence and foreign policy.',
    content: `India, US, Japan and Australia announce new initiatives for Indo-Pacific stability...`,
    readTime: '7 min',
    date: 'January 19, 2025',
    image: 'https://images.unsplash.com/photo-1532375810709-75b1da00537c?w=400&h=250&fit=crop',
    tags: ['#QUAD', '#IndoPacific', '#Security'],
    topic: 'International Relations',
    relatedIds: ['intl-2', 'intl-5'],
    hasQuiz: true,
    quizQuestions: 10,
  },
  {
    id: 'intl-4',
    title: 'BRICS Expansion: New Members Join Alliance',
    category: 'International',
    importance: 'high',
    excerpt: 'BRICS+ expansion with new partner countries. Changing global dynamics analysis.',
    content: `BRICS welcomes new members as the bloc expands its global influence...`,
    readTime: '8 min',
    date: 'January 18, 2025',
    image: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=400&h=250&fit=crop',
    tags: ['#BRICS', '#GlobalAlliance', '#Multilateral'],
    topic: 'International Relations',
    relatedIds: ['intl-3', 'intl-6'],
    hasQuiz: true,
    quizQuestions: 10,
  },
  {
    id: 'intl-5',
    title: 'India-UK Trade Agreement Finalized',
    category: 'International',
    importance: 'medium',
    excerpt: 'Comprehensive trade deal with United Kingdom signed. Market access implications.',
    content: `India and UK conclude negotiations on comprehensive trade agreement...`,
    readTime: '6 min',
    date: 'January 17, 2025',
    image: 'https://images.unsplash.com/photo-1486299267070-83823f5448dd?w=400&h=250&fit=crop',
    tags: ['#IndiaUK', '#FTA', '#Trade'],
    topic: 'International Relations',
    relatedIds: ['intl-4', 'intl-7'],
    hasQuiz: false,
  },
  {
    id: 'intl-6',
    title: 'UN Security Council Reform: India\'s Bid for Permanent Seat',
    category: 'International',
    importance: 'high',
    excerpt: 'Progress on UNSC reform and India\'s candidature. Important for UPSC aspirants.',
    content: `International support grows for UNSC expansion with India as permanent member...`,
    readTime: '7 min',
    date: 'January 16, 2025',
    image: 'https://images.unsplash.com/photo-1589262804704-c5aa9e6def89?w=400&h=250&fit=crop',
    tags: ['#UNSC', '#UNReform', '#India'],
    topic: 'International Relations',
    relatedIds: ['intl-5', 'intl-8'],
    hasQuiz: true,
    quizQuestions: 10,
  },
  {
    id: 'intl-7',
    title: 'SCO Summit: Regional Cooperation Initiatives',
    category: 'International',
    importance: 'medium',
    excerpt: 'Shanghai Cooperation Organisation meets. Central Asia and security cooperation.',
    content: `SCO leaders discuss regional security, trade and connectivity initiatives...`,
    readTime: '6 min',
    date: 'January 15, 2025',
    image: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=400&h=250&fit=crop',
    tags: ['#SCO', '#RegionalCooperation', '#CentralAsia'],
    topic: 'International Relations',
    relatedIds: ['intl-6', 'intl-9'],
    hasQuiz: false,
  },
  {
    id: 'intl-8',
    title: 'India-Middle East-Europe Corridor: IMEC Progress',
    category: 'International',
    importance: 'high',
    excerpt: 'Major connectivity initiative advances. Strategic trade corridor development.',
    content: `IMEC project gains momentum with new infrastructure agreements signed...`,
    readTime: '7 min',
    date: 'January 14, 2025',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=250&fit=crop',
    tags: ['#IMEC', '#Connectivity', '#Trade'],
    topic: 'International Relations',
    relatedIds: ['intl-7', 'intl-10'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'intl-9',
    title: 'Climate Finance Agreement at COP30',
    category: 'International',
    importance: 'high',
    excerpt: 'Historic climate finance deal reached. Implications for developing nations.',
    content: `Global agreement on climate finance with significant commitments for adaptation...`,
    readTime: '8 min',
    date: 'January 13, 2025',
    image: 'https://images.unsplash.com/photo-1569163139599-0f4517e36f51?w=400&h=250&fit=crop',
    tags: ['#COP30', '#ClimateFinance', '#Environment'],
    topic: 'International Relations',
    relatedIds: ['intl-8', 'intl-1'],
    hasQuiz: true,
    quizQuestions: 10,
  },
  {
    id: 'intl-10',
    title: 'India-Japan 2+2 Dialogue: Defence and Diplomacy',
    category: 'International',
    importance: 'medium',
    excerpt: 'Strategic partnership with Japan strengthened. Key outcomes of ministerial dialogue.',
    content: `India and Japan hold 2+2 dialogue with focus on defence cooperation...`,
    readTime: '5 min',
    date: 'January 12, 2025',
    image: 'https://images.unsplash.com/photo-1532375810709-75b1da00537c?w=400&h=250&fit=crop',
    tags: ['#IndiaJapan', '#2Plus2', '#Defence'],
    topic: 'International Relations',
    relatedIds: ['intl-9', 'intl-2'],
    hasQuiz: false,
  },

  // Environment - 10 Articles
  {
    id: 'env-1',
    title: 'National Green Hydrogen Mission: Progress Update',
    category: 'Science',
    importance: 'high',
    excerpt: 'India advances green hydrogen production targets. Clean energy transition update.',
    content: `Major progress in green hydrogen production with new manufacturing facilities...`,
    readTime: '7 min',
    date: 'January 20, 2025',
    image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400&h=250&fit=crop',
    tags: ['#GreenHydrogen', '#CleanEnergy', '#Environment'],
    topic: 'Environment',
    relatedIds: ['env-2', 'env-3'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'env-2',
    title: 'Tiger Population Crosses 3,500: Conservation Success',
    category: 'Science',
    importance: 'medium',
    excerpt: 'India\'s tiger conservation success story continues. Wildlife protection update.',
    content: `Latest tiger census shows India hosts over 70% of world\'s wild tiger population...`,
    readTime: '5 min',
    date: 'January 19, 2025',
    image: 'https://images.unsplash.com/photo-1549366021-9f761d450615?w=400&h=250&fit=crop',
    tags: ['#TigerConservation', '#Wildlife', '#Biodiversity'],
    topic: 'Environment',
    relatedIds: ['env-1', 'env-4'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'env-3',
    title: 'New Ramsar Sites: India Adds Wetlands to Protected List',
    category: 'Science',
    importance: 'medium',
    excerpt: 'Wetland conservation expanded with new Ramsar designations. Biodiversity update.',
    content: `India designates five new wetlands as Ramsar sites for conservation...`,
    readTime: '4 min',
    date: 'January 18, 2025',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=250&fit=crop',
    tags: ['#Ramsar', '#Wetlands', '#Conservation'],
    topic: 'Environment',
    relatedIds: ['env-2', 'env-5'],
    hasQuiz: true,
    quizQuestions: 6,
  },
  {
    id: 'env-4',
    title: 'Electric Vehicle Sales Cross 2 Million in 2024',
    category: 'Science',
    importance: 'high',
    excerpt: 'EV adoption accelerates in India. Green mobility transformation update.',
    content: `India achieves milestone in EV adoption with record sales in 2024...`,
    readTime: '6 min',
    date: 'January 17, 2025',
    image: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=400&h=250&fit=crop',
    tags: ['#ElectricVehicles', '#EV', '#GreenMobility'],
    topic: 'Environment',
    relatedIds: ['env-3', 'env-6'],
    hasQuiz: false,
  },
  {
    id: 'env-5',
    title: 'Renewable Energy Capacity Reaches 200 GW',
    category: 'Science',
    importance: 'high',
    excerpt: 'India achieves major renewable energy milestone. Solar and wind capacity expansion.',
    content: `India crosses 200 GW renewable energy capacity ahead of schedule...`,
    readTime: '6 min',
    date: 'January 16, 2025',
    image: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=400&h=250&fit=crop',
    tags: ['#RenewableEnergy', '#SolarPower', '#WindEnergy'],
    topic: 'Environment',
    relatedIds: ['env-4', 'env-7'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'env-6',
    title: 'Forest Cover Increases: State of Forest Report 2025',
    category: 'Science',
    importance: 'medium',
    excerpt: 'India\'s forest cover shows positive trend. ISFR key findings for exams.',
    content: `India State of Forest Report shows increase in forest and tree cover...`,
    readTime: '7 min',
    date: 'January 15, 2025',
    image: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=400&h=250&fit=crop',
    tags: ['#ForestCover', '#ISFR', '#Conservation'],
    topic: 'Environment',
    relatedIds: ['env-5', 'env-8'],
    hasQuiz: true,
    quizQuestions: 10,
  },
  {
    id: 'env-7',
    title: 'Air Quality Improvement: NCAP Progress Review',
    category: 'Science',
    importance: 'medium',
    excerpt: 'National Clean Air Programme shows results. Pollution control measures update.',
    content: `NCAP cities show improvement in air quality with reduced PM2.5 levels...`,
    readTime: '5 min',
    date: 'January 14, 2025',
    image: 'https://images.unsplash.com/photo-1569163139599-0f4517e36f51?w=400&h=250&fit=crop',
    tags: ['#AirQuality', '#NCAP', '#Pollution'],
    topic: 'Environment',
    relatedIds: ['env-6', 'env-9'],
    hasQuiz: false,
  },
  {
    id: 'env-8',
    title: 'Project Cheetah: One Year of Reintroduction',
    category: 'Science',
    importance: 'medium',
    excerpt: 'Cheetah reintroduction program review. Wildlife conservation milestone.',
    content: `Project Cheetah completes one year with breeding success in Kuno National Park...`,
    readTime: '6 min',
    date: 'January 13, 2025',
    image: 'https://images.unsplash.com/photo-1456926631375-92c8ce872def?w=400&h=250&fit=crop',
    tags: ['#ProjectCheetah', '#Wildlife', '#Conservation'],
    topic: 'Environment',
    relatedIds: ['env-7', 'env-10'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'env-9',
    title: 'Single-Use Plastic Ban: Implementation Status',
    category: 'Science',
    importance: 'medium',
    excerpt: 'Progress on eliminating single-use plastics. Environmental policy update.',
    content: `Review of single-use plastic ban implementation across states...`,
    readTime: '5 min',
    date: 'January 12, 2025',
    image: 'https://images.unsplash.com/photo-1604187351574-c75ca79f5807?w=400&h=250&fit=crop',
    tags: ['#PlasticBan', '#Environment', '#Sustainability'],
    topic: 'Environment',
    relatedIds: ['env-8', 'env-1'],
    hasQuiz: false,
  },
  {
    id: 'env-10',
    title: 'Mangrove Conservation: Coastal Ecosystem Protection',
    category: 'Science',
    importance: 'medium',
    excerpt: 'India expands mangrove protection. Blue carbon and coastal resilience.',
    content: `New mangrove conservation initiatives launched in coastal states...`,
    readTime: '5 min',
    date: 'January 11, 2025',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=250&fit=crop',
    tags: ['#Mangroves', '#CoastalEcosystem', '#Conservation'],
    topic: 'Environment',
    relatedIds: ['env-9', 'env-2'],
    hasQuiz: true,
    quizQuestions: 6,
  },

  // Education - 10 Articles
  {
    id: 'edu-1',
    title: 'National Education Policy 2020: Implementation Updates',
    category: 'Government',
    importance: 'high',
    excerpt: 'Latest NEP implementation progress and reforms. Essential for teaching and UPSC exams.',
    content: `Major progress in implementing NEP 2020 across higher education institutions...`,
    readTime: '8 min',
    date: 'January 20, 2025',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=400&h=250&fit=crop',
    tags: ['#NEP2020', '#Education', '#Reforms'],
    topic: 'Education',
    relatedIds: ['edu-2', 'edu-3'],
    hasQuiz: true,
    quizQuestions: 12,
  },
  {
    id: 'edu-2',
    title: 'AISHE Report 2024: Higher Education Statistics',
    category: 'Government',
    importance: 'medium',
    excerpt: 'All India Survey on Higher Education key findings. GER and enrollment data.',
    content: `AISHE 2024 shows improvement in Gross Enrollment Ratio and gender parity...`,
    readTime: '6 min',
    date: 'January 19, 2025',
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=400&h=250&fit=crop',
    tags: ['#AISHE', '#HigherEducation', '#GER'],
    topic: 'Education',
    relatedIds: ['edu-1', 'edu-4'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'edu-3',
    title: 'PM eVIDYA 2.0: Digital Education Platform Launch',
    category: 'Government',
    importance: 'medium',
    excerpt: 'Enhanced digital learning platform for students. E-learning initiatives update.',
    content: `PM eVIDYA 2.0 launched with improved content and accessibility features...`,
    readTime: '5 min',
    date: 'January 18, 2025',
    image: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=400&h=250&fit=crop',
    tags: ['#PMeVIDYA', '#DigitalEducation', '#ELearning'],
    topic: 'Education',
    relatedIds: ['edu-2', 'edu-5'],
    hasQuiz: false,
  },
  {
    id: 'edu-4',
    title: 'QS World University Rankings: Indian Universities Performance',
    category: 'Government',
    importance: 'medium',
    excerpt: 'Indian institutions improve in global rankings. Higher education quality update.',
    content: `Record number of Indian universities feature in QS World Rankings 2025...`,
    readTime: '5 min',
    date: 'January 17, 2025',
    image: 'https://images.unsplash.com/photo-1562774053-701939374585?w=400&h=250&fit=crop',
    tags: ['#QSRankings', '#Universities', '#Education'],
    topic: 'Education',
    relatedIds: ['edu-3', 'edu-6'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'edu-5',
    title: 'Academic Bank of Credits: Pan-India Implementation',
    category: 'Government',
    importance: 'medium',
    excerpt: 'ABC portal enables credit transfer across universities. NEP implementation milestone.',
    content: `Academic Bank of Credits now implemented across all central universities...`,
    readTime: '4 min',
    date: 'January 16, 2025',
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400&h=250&fit=crop',
    tags: ['#ABC', '#NEP', '#CreditTransfer'],
    topic: 'Education',
    relatedIds: ['edu-4', 'edu-7'],
    hasQuiz: false,
  },
  {
    id: 'edu-6',
    title: 'Skill India Mission: 10 Million Trained in 2024',
    category: 'Government',
    importance: 'high',
    excerpt: 'Major skill development milestone achieved. Employment and vocational training update.',
    content: `Skill India program achieves target with focus on emerging technologies...`,
    readTime: '6 min',
    date: 'January 15, 2025',
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400&h=250&fit=crop',
    tags: ['#SkillIndia', '#VocationalTraining', '#Employment'],
    topic: 'Education',
    relatedIds: ['edu-5', 'edu-8'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'edu-7',
    title: 'NIPUN Bharat: Foundational Literacy Progress',
    category: 'Government',
    importance: 'medium',
    excerpt: 'National initiative for reading and numeracy shows results. Primary education update.',
    content: `NIPUN Bharat mission improves foundational literacy rates in target states...`,
    readTime: '5 min',
    date: 'January 14, 2025',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=400&h=250&fit=crop',
    tags: ['#NIPUNBharat', '#Literacy', '#PrimaryEducation'],
    topic: 'Education',
    relatedIds: ['edu-6', 'edu-9'],
    hasQuiz: true,
    quizQuestions: 6,
  },
  {
    id: 'edu-8',
    title: 'Foreign University Campuses in India: GIFT City Update',
    category: 'Government',
    importance: 'high',
    excerpt: 'International universities set up campuses in India. Higher education internationalization.',
    content: `Top global universities announce campus plans in GIFT City and other locations...`,
    readTime: '6 min',
    date: 'January 13, 2025',
    image: 'https://images.unsplash.com/photo-1562774053-701939374585?w=400&h=250&fit=crop',
    tags: ['#ForeignUniversities', '#GIFTCity', '#HigherEducation'],
    topic: 'Education',
    relatedIds: ['edu-7', 'edu-10'],
    hasQuiz: false,
  },
  {
    id: 'edu-9',
    title: 'National Apprenticeship Training Scheme Expansion',
    category: 'Government',
    importance: 'medium',
    excerpt: 'NATS program expands with industry partnerships. Skill-to-employment linkage.',
    content: `NATS enrollment increases with new partnerships in manufacturing and IT sectors...`,
    readTime: '5 min',
    date: 'January 12, 2025',
    image: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=400&h=250&fit=crop',
    tags: ['#NATS', '#Apprenticeship', '#Employment'],
    topic: 'Education',
    relatedIds: ['edu-8', 'edu-1'],
    hasQuiz: false,
  },
  {
    id: 'edu-10',
    title: 'One Nation One Examination: Common University Entrance Test',
    category: 'Government',
    importance: 'high',
    excerpt: 'CUET becomes mandatory for central university admissions. Exam reform update.',
    content: `CUET 2025 preparation with expanded test cities and improved infrastructure...`,
    readTime: '6 min',
    date: 'January 11, 2025',
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400&h=250&fit=crop',
    tags: ['#CUET', '#Examination', '#UniversityAdmission'],
    topic: 'Education',
    relatedIds: ['edu-9', 'edu-2'],
    hasQuiz: true,
    quizQuestions: 10,
  },

  // Digital India - 10 Articles
  {
    id: 'digital-1',
    title: 'Digital India 3.0: Next Phase of Digital Transformation',
    category: 'Government',
    importance: 'high',
    excerpt: 'Government launches enhanced digital initiatives. E-governance and technology update.',
    content: `Digital India 3.0 focuses on AI integration and rural connectivity...`,
    readTime: '7 min',
    date: 'January 21, 2025',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=250&fit=crop',
    tags: ['#DigitalIndia', '#EGovernance', '#Technology'],
    topic: 'Digital India',
    relatedIds: ['digital-2', 'digital-3'],
    hasQuiz: true,
    quizQuestions: 10,
  },
  {
    id: 'digital-2',
    title: 'BharatNet Phase 3: Rural Internet Connectivity',
    category: 'Government',
    importance: 'medium',
    excerpt: 'Optical fiber reaches more villages. Digital infrastructure expansion update.',
    content: `BharatNet Phase 3 connects additional villages with high-speed internet...`,
    readTime: '5 min',
    date: 'January 20, 2025',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=250&fit=crop',
    tags: ['#BharatNet', '#RuralInternet', '#Connectivity'],
    topic: 'Digital India',
    relatedIds: ['digital-1', 'digital-4'],
    hasQuiz: false,
  },
  {
    id: 'digital-3',
    title: 'Aadhaar Enabled Services: New Use Cases Launched',
    category: 'Government',
    importance: 'medium',
    excerpt: 'Aadhaar integration expands to new sectors. Digital identity applications.',
    content: `UIDAI launches new Aadhaar-enabled services for financial inclusion...`,
    readTime: '5 min',
    date: 'January 19, 2025',
    image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=400&h=250&fit=crop',
    tags: ['#Aadhaar', '#DigitalIdentity', '#Finclusion'],
    topic: 'Digital India',
    relatedIds: ['digital-2', 'digital-5'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'digital-4',
    title: 'DigiLocker 2.0: Enhanced Document Storage',
    category: 'Government',
    importance: 'medium',
    excerpt: 'DigiLocker platform upgraded with new features. Digital document management.',
    content: `DigiLocker 2.0 launched with improved security and cross-platform access...`,
    readTime: '4 min',
    date: 'January 18, 2025',
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&h=250&fit=crop',
    tags: ['#DigiLocker', '#DigitalDocuments', '#EGovernance'],
    topic: 'Digital India',
    relatedIds: ['digital-3', 'digital-6'],
    hasQuiz: false,
  },
  {
    id: 'digital-5',
    title: 'CoWIN Platform Repurposed for Health Services',
    category: 'Government',
    importance: 'medium',
    excerpt: 'Successful vaccination platform expanded for broader health services.',
    content: `CoWIN technology leveraged for universal health services delivery...`,
    readTime: '5 min',
    date: 'January 17, 2025',
    image: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=400&h=250&fit=crop',
    tags: ['#CoWIN', '#DigitalHealth', '#Technology'],
    topic: 'Digital India',
    relatedIds: ['digital-4', 'digital-7'],
    hasQuiz: false,
  },
  {
    id: 'digital-6',
    title: 'National AI Portal: Artificial Intelligence Initiatives',
    category: 'Government',
    importance: 'high',
    excerpt: 'India\'s AI strategy and national portal updates. Technology policy for exams.',
    content: `National AI Portal expanded with new resources and industry partnerships...`,
    readTime: '6 min',
    date: 'January 16, 2025',
    image: 'https://images.unsplash.com/photo-1555255707-c07966088b7b?w=400&h=250&fit=crop',
    tags: ['#AI', '#NationalAIPortal', '#Technology'],
    topic: 'Digital India',
    relatedIds: ['digital-5', 'digital-8'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'digital-7',
    title: 'UMANG App: New Services Added',
    category: 'Government',
    importance: 'medium',
    excerpt: 'Unified Mobile Application adds more government services. Single app governance.',
    content: `UMANG now offers over 1500 services from central and state governments...`,
    readTime: '4 min',
    date: 'January 15, 2025',
    image: 'https://images.unsplash.com/photo-1556656793-08538906a9f8?w=400&h=250&fit=crop',
    tags: ['#UMANG', '#MobileGovernance', '#EServices'],
    topic: 'Digital India',
    relatedIds: ['digital-6', 'digital-9'],
    hasQuiz: false,
  },
  {
    id: 'digital-8',
    title: 'National Supercomputing Mission: Param Siddhi Update',
    category: 'Government',
    importance: 'medium',
    excerpt: 'Indigenous supercomputing capabilities enhanced. High-performance computing.',
    content: `India adds new supercomputers under National Supercomputing Mission...`,
    readTime: '5 min',
    date: 'January 14, 2025',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&h=250&fit=crop',
    tags: ['#Supercomputer', '#ParamSiddhi', '#HPC'],
    topic: 'Digital India',
    relatedIds: ['digital-7', 'digital-10'],
    hasQuiz: true,
    quizQuestions: 6,
  },
  {
    id: 'digital-9',
    title: 'Cyber Security Framework: New Guidelines Released',
    category: 'Government',
    importance: 'high',
    excerpt: 'Enhanced cybersecurity measures for critical infrastructure. Security policy update.',
    content: `Government releases comprehensive cybersecurity framework for digital India...`,
    readTime: '6 min',
    date: 'January 13, 2025',
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop',
    tags: ['#CyberSecurity', '#DigitalSafety', '#Policy'],
    topic: 'Digital India',
    relatedIds: ['digital-8', 'digital-1'],
    hasQuiz: true,
    quizQuestions: 10,
  },
  {
    id: 'digital-10',
    title: '5G Rollout: Coverage Reaches 500 Cities',
    category: 'Government',
    importance: 'high',
    excerpt: '5G network expansion accelerates. Telecom infrastructure development update.',
    content: `5G coverage expands to 500 cities with focus on industrial applications...`,
    readTime: '5 min',
    date: 'January 12, 2025',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=250&fit=crop',
    tags: ['#5G', '#Telecom', '#Connectivity'],
    topic: 'Digital India',
    relatedIds: ['digital-9', 'digital-2'],
    hasQuiz: true,
    quizQuestions: 8,
  },

  // Infrastructure - 10 Articles
  {
    id: 'infra-1',
    title: 'New Railway Projects Announced for Northeast',
    category: 'National',
    importance: 'high',
    excerpt: 'Railway Ministry announces connectivity projects worth ₹25,000 crores. Important for RRB exams.',
    content: `Comprehensive connectivity enhancement program for Northeast region announced...`,
    readTime: '6 min',
    date: 'January 21, 2025',
    image: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=400&h=250&fit=crop',
    tags: ['#Railways', '#Infrastructure', '#Northeast'],
    topic: 'Infrastructure',
    relatedIds: ['infra-2', 'infra-3'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'infra-2',
    title: 'Vande Bharat: 100 Trains Now Operational',
    category: 'National',
    importance: 'high',
    excerpt: 'Major milestone in semi-high speed rail network. Railway modernization update.',
    content: `India achieves 100 Vande Bharat trains target with new routes announced...`,
    readTime: '5 min',
    date: 'January 20, 2025',
    image: 'https://images.unsplash.com/photo-1532377449966-1f299f7e4c3a?w=400&h=250&fit=crop',
    tags: ['#VandeBharat', '#Railways', '#HighSpeedRail'],
    topic: 'Infrastructure',
    relatedIds: ['infra-1', 'infra-4'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'infra-3',
    title: 'Mumbai-Ahmedabad Bullet Train: Construction Progress',
    category: 'National',
    importance: 'high',
    excerpt: 'India\'s first bullet train project advances. High-speed rail development update.',
    content: `MAHSR project achieves significant construction milestones with Japanese technology...`,
    readTime: '7 min',
    date: 'January 19, 2025',
    image: 'https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=400&h=250&fit=crop',
    tags: ['#BulletTrain', '#MAHSR', '#HighSpeedRail'],
    topic: 'Infrastructure',
    relatedIds: ['infra-2', 'infra-5'],
    hasQuiz: false,
  },
  {
    id: 'infra-4',
    title: 'National Highway Development: 50,000 km Target',
    category: 'National',
    importance: 'medium',
    excerpt: 'Bharatmala and highway expansion progress. Road infrastructure update.',
    content: `India accelerates highway construction under Bharatmala Pariyojana...`,
    readTime: '6 min',
    date: 'January 18, 2025',
    image: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=400&h=250&fit=crop',
    tags: ['#Highways', '#Bharatmala', '#Roads'],
    topic: 'Infrastructure',
    relatedIds: ['infra-3', 'infra-6'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'infra-5',
    title: 'New Airports: UDAN Regional Connectivity',
    category: 'National',
    importance: 'medium',
    excerpt: 'Regional air connectivity expanded. Aviation infrastructure development.',
    content: `UDAN scheme operationalizes new airports improving regional connectivity...`,
    readTime: '5 min',
    date: 'January 17, 2025',
    image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=400&h=250&fit=crop',
    tags: ['#UDAN', '#Airports', '#Aviation'],
    topic: 'Infrastructure',
    relatedIds: ['infra-4', 'infra-7'],
    hasQuiz: false,
  },
  {
    id: 'infra-6',
    title: 'Sagarmala Project: Port Infrastructure Update',
    category: 'National',
    importance: 'medium',
    excerpt: 'Port-led development and maritime infrastructure. Blue economy initiatives.',
    content: `Sagarmala project enhances port capacity and coastal shipping...`,
    readTime: '6 min',
    date: 'January 16, 2025',
    image: 'https://images.unsplash.com/photo-1494412651409-8963ce7935a7?w=400&h=250&fit=crop',
    tags: ['#Sagarmala', '#Ports', '#Maritime'],
    topic: 'Infrastructure',
    relatedIds: ['infra-5', 'infra-8'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'infra-7',
    title: 'Metro Rail Expansion: 1000 km Network Achieved',
    category: 'National',
    importance: 'high',
    excerpt: 'Urban rail transit milestone reached. Metro connectivity in Indian cities.',
    content: `India crosses 1000 km operational metro rail network across cities...`,
    readTime: '5 min',
    date: 'January 15, 2025',
    image: 'https://images.unsplash.com/photo-1565957011369-9c1c98cf7bc9?w=400&h=250&fit=crop',
    tags: ['#MetroRail', '#UrbanTransit', '#Infrastructure'],
    topic: 'Infrastructure',
    relatedIds: ['infra-6', 'infra-9'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'infra-8',
    title: 'Smart Cities Mission: Phase 2 Progress',
    category: 'National',
    importance: 'medium',
    excerpt: 'Urban development under Smart Cities Mission. City infrastructure modernization.',
    content: `Smart Cities Mission Phase 2 focuses on sustainability and digital infrastructure...`,
    readTime: '6 min',
    date: 'January 14, 2025',
    image: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=400&h=250&fit=crop',
    tags: ['#SmartCities', '#UrbanDevelopment', '#Infrastructure'],
    topic: 'Infrastructure',
    relatedIds: ['infra-7', 'infra-10'],
    hasQuiz: false,
  },
  {
    id: 'infra-9',
    title: 'Atal Tunnel: High Altitude Infrastructure',
    category: 'National',
    importance: 'medium',
    excerpt: 'Strategic tunnel developments in Himalayan region. Mountain connectivity update.',
    content: `New tunnel projects in Himalayas enhance border connectivity...`,
    readTime: '5 min',
    date: 'January 13, 2025',
    image: 'https://images.unsplash.com/photo-1473445730015-841f29a9490b?w=400&h=250&fit=crop',
    tags: ['#Tunnels', '#BorderInfra', '#Himalayas'],
    topic: 'Infrastructure',
    relatedIds: ['infra-8', 'infra-1'],
    hasQuiz: false,
  },
  {
    id: 'infra-10',
    title: 'Dedicated Freight Corridors: Eastern DFC Completion',
    category: 'National',
    importance: 'high',
    excerpt: 'Major freight rail corridor completed. Logistics infrastructure development.',
    content: `Eastern Dedicated Freight Corridor fully operational boosting logistics...`,
    readTime: '6 min',
    date: 'January 12, 2025',
    image: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=400&h=250&fit=crop',
    tags: ['#DFC', '#FreightCorridor', '#Logistics'],
    topic: 'Infrastructure',
    relatedIds: ['infra-9', 'infra-2'],
    hasQuiz: true,
    quizQuestions: 8,
  },

  // Health - 10 Articles
  {
    id: 'health-1',
    title: 'Ayushman Bharat: Coverage Crosses 50 Crore Beneficiaries',
    category: 'Government',
    importance: 'high',
    excerpt: 'World\'s largest health insurance scheme milestone. Healthcare coverage update.',
    content: `Ayushman Bharat PMJAY crosses 50 crore beneficiary milestone...`,
    readTime: '6 min',
    date: 'January 20, 2025',
    image: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=400&h=250&fit=crop',
    tags: ['#AyushmanBharat', '#PMJAY', '#Healthcare'],
    topic: 'Health',
    relatedIds: ['health-2', 'health-3'],
    hasQuiz: true,
    quizQuestions: 10,
  },
  {
    id: 'health-2',
    title: 'AIIMS Expansion: 22 New Institutions Operational',
    category: 'Government',
    importance: 'medium',
    excerpt: 'Medical education infrastructure expansion. Healthcare access improvement.',
    content: `All 22 new AIIMS institutions are now fully operational across India...`,
    readTime: '5 min',
    date: 'January 19, 2025',
    image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=400&h=250&fit=crop',
    tags: ['#AIIMS', '#MedicalEducation', '#Healthcare'],
    topic: 'Health',
    relatedIds: ['health-1', 'health-4'],
    hasQuiz: false,
  },
  {
    id: 'health-3',
    title: 'National Health Mission: Rural Healthcare Strengthening',
    category: 'Government',
    importance: 'medium',
    excerpt: 'Primary healthcare improvement in rural areas. NHM achievements update.',
    content: `NHM strengthens primary healthcare infrastructure in rural India...`,
    readTime: '5 min',
    date: 'January 18, 2025',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=400&h=250&fit=crop',
    tags: ['#NHM', '#RuralHealthcare', '#PrimaryHealth'],
    topic: 'Health',
    relatedIds: ['health-2', 'health-5'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'health-4',
    title: 'TB Elimination: India Accelerates 2025 Target',
    category: 'Government',
    importance: 'high',
    excerpt: 'Tuberculosis elimination progress and new strategies. Public health update.',
    content: `India intensifies TB elimination efforts with new treatment protocols...`,
    readTime: '6 min',
    date: 'January 17, 2025',
    image: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&h=250&fit=crop',
    tags: ['#TBElimination', '#PublicHealth', '#Healthcare'],
    topic: 'Health',
    relatedIds: ['health-3', 'health-6'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'health-5',
    title: 'Jan Aushadhi: Affordable Medicine Access Expanded',
    category: 'Government',
    importance: 'medium',
    excerpt: 'Generic medicine stores cross 10,000 outlets. Affordable healthcare initiative.',
    content: `Pradhan Mantri Jan Aushadhi Kendras now exceed 10,000 across India...`,
    readTime: '4 min',
    date: 'January 16, 2025',
    image: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400&h=250&fit=crop',
    tags: ['#JanAushadhi', '#GenericMedicine', '#Affordable'],
    topic: 'Health',
    relatedIds: ['health-4', 'health-7'],
    hasQuiz: false,
  },
  {
    id: 'health-6',
    title: 'National Digital Health Mission: ABHA Registration',
    category: 'Government',
    importance: 'high',
    excerpt: 'Digital health ID adoption accelerates. Health record digitization update.',
    content: `Ayushman Bharat Health Account registrations cross 50 crore mark...`,
    readTime: '5 min',
    date: 'January 15, 2025',
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400&h=250&fit=crop',
    tags: ['#NDHM', '#ABHA', '#DigitalHealth'],
    topic: 'Health',
    relatedIds: ['health-5', 'health-8'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'health-7',
    title: 'Mission Indradhanush: Immunization Coverage Update',
    category: 'Government',
    importance: 'medium',
    excerpt: 'Universal immunization program progress. Child health protection initiatives.',
    content: `Intensified Mission Indradhanush achieves record vaccination coverage...`,
    readTime: '5 min',
    date: 'January 14, 2025',
    image: 'https://images.unsplash.com/photo-1578496479914-7ef3b0193be3?w=400&h=250&fit=crop',
    tags: ['#MissionIndradhanush', '#Vaccination', '#ChildHealth'],
    topic: 'Health',
    relatedIds: ['health-6', 'health-9'],
    hasQuiz: true,
    quizQuestions: 8,
  },
  {
    id: 'health-8',
    title: 'AYUSH Integration: Traditional Medicine in Healthcare',
    category: 'Government',
    importance: 'medium',
    excerpt: 'Ayurveda and traditional medicine integration in mainstream healthcare.',
    content: `AYUSH ministry integrates traditional medicine with modern healthcare...`,
    readTime: '5 min',
    date: 'January 13, 2025',
    image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=400&h=250&fit=crop',
    tags: ['#AYUSH', '#Ayurveda', '#TraditionalMedicine'],
    topic: 'Health',
    relatedIds: ['health-7', 'health-10'],
    hasQuiz: false,
  },
  {
    id: 'health-9',
    title: 'Medical Device Manufacturing: PLI Scheme Results',
    category: 'Government',
    importance: 'medium',
    excerpt: 'Indigenous medical device production increases. Healthcare manufacturing update.',
    content: `PLI scheme boosts domestic medical device manufacturing significantly...`,
    readTime: '5 min',
    date: 'January 12, 2025',
    image: 'https://images.unsplash.com/photo-1581595219315-a187dd40c322?w=400&h=250&fit=crop',
    tags: ['#MedicalDevices', '#PLI', '#Manufacturing'],
    topic: 'Health',
    relatedIds: ['health-8', 'health-1'],
    hasQuiz: false,
  },
  {
    id: 'health-10',
    title: 'Mental Health: Tele-MANAS Service Expansion',
    category: 'Government',
    importance: 'high',
    excerpt: 'Digital mental health services reach more people. Mental wellness initiatives.',
    content: `Tele-MANAS helpline expands with AI-powered counseling support...`,
    readTime: '5 min',
    date: 'January 11, 2025',
    image: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400&h=250&fit=crop',
    tags: ['#MentalHealth', '#TeleMANAS', '#Wellness'],
    topic: 'Health',
    relatedIds: ['health-9', 'health-2'],
    hasQuiz: true,
    quizQuestions: 8,
  },
];

export const getArticleById = (id: string): Article | undefined => {
  return allArticles.find(article => article.id === id);
};

export const getRelatedArticles = (article: Article): Article[] => {
  return allArticles.filter(a => article.relatedIds.includes(a.id));
};

export const getArticlesByTopic = (topic: string): Article[] => {
  return allArticles.filter(a => a.topic === topic);
};

export const getAllTopics = (): string[] => {
  const topics = new Set(allArticles.map(a => a.topic));
  return Array.from(topics);
};
